#!name=Apple WLOC 定位修改
#!desc=修改 Apple 网络定位返回坐标(经纬度+精度+海拔) (Shadowrocket ) | 选点页面: 请使用自建 wloc-geo Worker
#!author=Yu9191 Rewrite
#!homepage=https://github.com/zouyxinguk/wloc-geo
#!icon=https://raw.githubusercontent.com/zouyxinguk/wloc/refs/heads/main/wloc.jpg
#!category=Tools

[Script]
Apple WLOC = type=http-response,pattern=^https?:\/\/gs-loc(-cn)?\.apple\.com\/clls\/wloc,requires-body=1,binary-body-mode=1,max-size=0,timeout=30,script-path=https://raw.githubusercontent.com/zouyxinguk/wloc-geo/refs/heads/main/dist/wloc.js,argument=longitude=113.94114&latitude=22.544577&accuracy=25&altitude=15&logLevel=info
WLOC Settings = type=http-request,pattern=^https?:\/\/gs-loc(-cn)?\.apple\.com\/wloc-settings\/save,requires-body=0,max-size=0,timeout=10,script-path=https://raw.githubusercontent.com/zouyxinguk/wloc-geo/refs/heads/main/dist/wloc-settings.js

[MITM]
hostname = %APPEND% gs-loc.apple.com, gs-loc-cn.apple.com
